# Generated by Django 3.2.3 on 2021-05-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('solution', models.CharField(max_length=500, verbose_name='Solução')),
                ('responsible', models.CharField(choices=[('AN', 'André Rodrigues'), ('WN', 'Wanderson Neres'), ('DS', 'Daniel Santos')], max_length=50, verbose_name='Responsável')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('AVERAGE', 'Média'), ('HIGH', 'Alta')], max_length=50, verbose_name='Prioridade')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_in', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('finalized_in', models.DateTimeField(blank=True, verbose_name='Finalizado em')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'tarefas',
            },
        ),
    ]
