# Generated by Django 3.2.3 on 2021-05-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210525_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_in',
        ),
        migrations.AlterModelTable(
            name='task',
            table='TBTarefas',
        ),
    ]
