# Generated by Django 3.2.3 on 2021-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210525_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finalized_in',
            field=models.DateTimeField(verbose_name='Finalizado em'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(max_length=500, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título'),
        ),
    ]
