# Generated by Django 3.2.3 on 2021-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_finalized_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finalized_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
    ]
