# Generated by Django 3.2.3 on 2021-05-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_finalized_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(max_length=500, null=True, verbose_name='Solução'),
        ),
    ]
