# Generated by Django 3.2.3 on 2021-06-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.CharField(blank=True, choices=[('system change', 'Alteração de Sistema'), ('problem', 'Problema')], max_length=50, verbose_name='Tipo da Tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=8000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Título'),
        ),
    ]
