# Generated by Django 3.2.3 on 2021-09-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210619_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=12000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.CharField(choices=[('AN', 'André Rodrigues'), ('WN', 'Wanderson Neres'), ('DS', 'Daniel Santos'), ('GS', 'Gláucio de Souza'), ('LC', 'Lumi Cassandra'), ('RG', 'Ricardo Galante')], max_length=50, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, max_length=12000, null=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.CharField(blank=True, choices=[('system change', 'Alteração de Sistema'), ('problem', 'Problema'), ('new feature', 'Novo Recurso'), ('sticky notes', 'Lembretes')], max_length=50, verbose_name='Tipo da Tarefa'),
        ),
    ]
